default_language_version:
    python: python3
repos:
-   repo: local
    hooks:
    -   id: colrev-hooks-format
        name: "CoLRev ReviewManager: format"
        entry: colrev-hooks-format
        language: python
        stages: [commit]
        pass_filenames: false
    -   id: colrev-hooks-check
        name: "CoLRev ReviewManager: check"
        entry: colrev-hooks-check
        language: python
        stages: [commit]
        pass_filenames: false
    -   id: colrev-hooks-report
        name: "CoLRev ReviewManager: report"
        entry: colrev-hooks-report
        language: python
        stages: [prepare-commit-msg]
    -   id: colrev-hooks-share
        name: "CoLRev ReviewManager: share"
        entry: colrev-hooks-share
        language: python
        stages: [push]
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        stages: [commit]
